### ISSUE TITLE
Should we have a master branch?

### ISSUE THREAD

**Issue by jbauschatz** [ConchordanceProject/ConchordanceWeb#45]
Should we use "gh-pages" as the master branch?

I think so, since it seems redundant to merge into master, and then merge master into gh-pages.

It just means that we should carefully test our merges locally instead of relying on github to do it flawlessly, since as soon as we merge into gh-pages that goes live.

@civilframe @forana

**Comment by forana** [comment]
imo it's fine to use `gh-pages` as `master`. If github let us specify which branch to use for pages, I'd argue for `master`, but we can't.

**Comment by jbauschatz** [comment]
Sounds good. I have deleted master and made gh-pages the default branch.
